### ISSUE TITLE
Installing 2.3.12: ValueError: bad marshal data (unknown type code) 

### ISSUE THREAD

**Issue by steevee** [encode/django-rest-framework#1357]
When installing  djangorestframework 2.3.12 via easy_install I got the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1992, in main
    with_ei_usage(lambda:
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1979, in with_ei_usage
    return f()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1996, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 653, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 849, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1130, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1115, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 69, in run_setup
    lambda: execfile(
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 120, in run
    return func()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/sandbox.py", line 71, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 76, in <module>

  File "/usr/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 232, in run
    os.path.join(archive_root,'EGG-INFO'), self.zip_safe()
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 271, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 407, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/local/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 438, in scan_module
    code = marshal.load(f); f.close()
ValueError: bad marshal data (unknown type code)
An error occurred when trying to install djangorestframework 2.3.12
```

Similar to #1236 

Reverting to 2.3.10 was fine.

**Comment by abersh** [comment]
when i install  django-mptt-0.8.3.tar  "ValueError: bad marshal data (unknown type code)"
please help me !!!
