### ISSUE TITLE
POST tries to update existing entry

### ISSUE THREAD

**Issue by ierror** [encode/django-rest-framework#235]
Hello together,
i'm trying to get into django-rest-framework by following the _Blog Posts API_ example.
The first POST works like expected, but if i fire a second POST the rest-framework tries to update the previous added entry.

Please let me know if you need some more information.

Thanks for the project and best regards,
Boerni  
- django 1.4
- django-rest-framework 0.3.3

`Traceback (most recent call last):
  File "[...]virtualenv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "[...]virtualenv/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 67, in __call__
    return self.application(environ, start_response)
  File "[...]virtualenv/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 241, in __call__
    response = self.get_response(request)
  File "[...]virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 179, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "[...]virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 221, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "[...]virtualenv/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "[...]virtualenv/lib/python2.7/site-packages/django/views/generic/base.py", line 48, in view
    return self.dispatch(request, *args, **kwargs)
  File "[...]virtualenv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 77, in wrapped_view
    return view_func(*args, **kwargs)
  File "[...]virtualenv/lib/python2.7/site-packages/djangorestframework/views.py", line 234, in dispatch
    response_obj = handler(request, *args, **kwargs)
  File "[...]virtualenv/lib/python2.7/site-packages/djangorestframework/mixins.py", line 586, in post
    instance.save()
  File "[...]virtualenv/lib/python2.7/site-packages/django/db/models/base.py", line 463, in save
    self.save_base(using=using, force_insert=force_insert, force_update=force_update)
  File "[...]virtualenv/lib/python2.7/site-packages/django/db/models/base.py", line 529, in save_base
    rows = manager.using(using).filter(pk=pk_val)._update(values)
  File "[...]virtualenv/lib/python2.7/site-packages/django/db/models/query.py", line 557, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "[...]virtualenv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 986, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "[...]virtualenv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 818, in execute_sql
    cursor.execute(sql, params)
  File "[...]virtualenv/lib/python2.7/site-packages/django/db/backends/util.py", line 40, in execute
    return self.cursor.execute(sql, params)
  File "[...]virtualenv/lib/python2.7/site-packages/django/db/backends/postgresql_psycopg2/base.py", line 52, in execute
    return self.cursor.execute(query, args)
IntegrityError: null value in column "created" violates not-null constraint`

**Comment by danigarciaalva** [comment]
I have the same error, but I can't solve it, can you help me? Please

**Comment by xordoquy** [comment]
Please use the mailing list for usage questions.
