### ISSUE TITLE
rest : 3.6.3  django: 1.11.1   use : listField   when: perform_update

### ISSUE THREAD

**Issue by XinMa1** [encode/django-rest-framework#5201]
## anyone help me.

Internal Server Error: /dictpolicy/25/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/local/lib/python2.7/dist-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py", line 703, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py", line 637, in get_context
    raw_data_put_form = self.get_raw_data_form(data, view, 'PUT', request)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/renderers.py", line 559, in get_raw_data_form
    content = renderer.render(serializer.data, accepted, context)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 534, in data
    ret = super(Serializer, self).data
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 263, in data
    self._data = self.to_representation(self.instance)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/serializers.py", line 501, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 1573, in to_representation
    return [self.child.to_representation(item) if item is not None else None for item in data]
  File "/usr/local/lib/python2.7/dist-packages/rest_framework/fields.py", line 913, in to_representation
    return int(value)
ValueError: invalid literal for int() with base 10: '['

**Comment by XinMa1** [comment]
##  serializers.py
- [ ]  policy = serializers.ListField(child=serializers.IntegerField())

**Comment by mathpresso-mom** [comment]
Can we see your views?

**Comment by XinMa1** [comment]
##  接口操作


class modelAyOperateView(generics.RetrieveUpdateDestroyAPIView):
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = modelASerializer
    pagination_class = CommonPagination
    queryset = modelA.objects.all()

    def get(self, request, *args, **kwargs):
        user = request.user
        obj = generics.get_object_or_404(
            modelA, id=self.kwargs['pk'],
            hide=0, user=self.request.user)
        data = {
            'name': obj.name, 'id': self.kwargs['pk'],
            'policy': json.loads(obj.policy), 'date': obj.date,
            'user': obj.user.id}

        return Response(data, status=status.HTTP_200_OK)

    def perform_update(self, serializer, *args, **kwargs):
        # instance = serializer.save()

        data = self.request.data
     
        model_a = modelA.objects.get(
            id=self.kwargs['pk'], hide=0, user=self.request.user)
        model_a.name = data['name']
        model_a.policy = data['policy']
        model_a.save()

**Comment by mathpresso-mom** [comment]
It seems when you get policy from data,
`model_a.policy = data['policy']`
you got a string value. can you checkout your data type?

**Comment by XinMa1** [comment]
Type is list. for ture, I update success, But listField checking error for 500 error.

**Comment by mathpresso-mom** [comment]
How about models? As we know, [django cannot deal with list as a field.](https://stackoverflow.com/a/22343962)

**Comment by XinMa1** [comment]
just servializers.py  
## policy = serializers.ListField(child=serializers.IntegerField())
models.py as a TextField
## policy = models.TextField()

**Comment by xordoquy** [comment]
The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!
