### ISSUE TITLE
DateTimeField not validated properly

### ISSUE THREAD

**Issue by dolohow** [encode/django-rest-framework#5220]
## Steps to reproduce
1. Create model with `DateTimeField` property.
2. Use `ModelSerializer` to create serializer for a view.
3. Create view that will use this serializer.
4. Send `2017-08-16 22:00-24:00`

## Expected behavior
DRF replies with error saying that format of date is invalid, like if you would put `2017-08-16 24:00`

## Actual behavior
Application crashes with following stack trace:
```Internal Server Error: /orders/
Traceback (most recent call last):
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/rest_framework/views.py", line 474, in dispatch
    response = self.handle_exception(exc)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/rest_framework/views.py", line 434, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/rest_framework/views.py", line 471, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/rest_framework/generics.py", line 191, in post
    return self.create(request, *args, **kwargs)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/rest_framework/mixins.py", line 20, in create
    serializer.is_valid(raise_exception=True)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/rest_framework/serializers.py", line 214, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/rest_framework/serializers.py", line 408, in run_validation
    value = self.to_internal_value(data)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/rest_framework/serializers.py", line 438, in to_internal_value
    validated_value = field.run_validation(primitive_value)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/rest_framework/fields.py", line 490, in run_validation
    value = self.to_internal_value(data)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/rest_framework/fields.py", line 1087, in to_internal_value
    return self.enforce_timezone(parsed)
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/rest_framework/fields.py", line 1061, in enforce_timezone
    if (field_timezone is not None) and not timezone.is_aware(value):
  File "/home/app/.virtualenvs/djangodev/lib/python3.5/site-packages/django/utils/timezone.py", line 344, in is_aware
    return value.utcoffset() is not None
ValueError: offset must be a timedelta strictly between -timedelta(hours=24) and timedelta(hours=24).
```

**Comment by xordoquy** [comment]
Question here would be to figure out whether it's a Django bug or a DRF one.

**Comment by vimarshc** [comment]
I would like to take this up.

**Comment by vimarshc** [comment]
@xordoquy 
Is the expected behaviour is for the is_valid() function to return False right and not crash?

**Comment by xordoquy** [comment]
@vimarshc it should not crash but... Django's `timezone.is_aware` shouldn't crash either I think.
Let's make sure it doesn't crash without assuming of Django's behavior then.
