### ISSUE TITLE
APIClient() asks for serializer_class even though the post method is overridden inside view

### ISSUE THREAD

**Issue by royalpranjal** [encode/django-rest-framework#5356]
I am write the tests for my project.

```
# tests.py 
class customeTests(APITestCase):
    def setup(self):
         # some code
  
    def test_checkAPostRequest(self):
           url = "some_url"
           response = self.client.post(url, header="some_header", data="some_data")
           # Further code

# views.py
class SomePostView(CreateAPIView):
     def post(self, request, *args, **kwargs):
           # custom logic
```
##########################
When I run my tests, I get an error saying that 
` SomePostView must either include a serializer_class or override get_serializer_class()`

Why is this happening? I checked the API on postman. It's running fine. 
FYI - It's only happening in views where I haven't specified a serializer_class (used custom logic instead)

**Comment by xordoquy** [comment]
what's the associated traceback ?

**Comment by tomchristie** [comment]
If the logic is entirely custom then you probably don't want to be overriding `CreateAPIView`, but rather just `APIView`.

Anyways, something in your codebase is calling into the view's `get_queryset` one way or another, which cannot succeed as there's no queryset declared on the view. As @xordoquy alludes, having a look at the traceback should help you figure out where that's being called into.

**Comment by royalpranjal** [comment]
Still even if I am using `CreateAPIView', it should not ask for the `serializer_class` or the 'queryset' if I am overriding everything!!

**Comment by tomchristie** [comment]
> it should not ask for

We can reconsider the "it should not ask for" once there's a traceback that gives a clear indication of *what*'s being called into & *where*. As it stands it's not clear if it's something that's being called into ultimately as a result of user code, or as a result of framework code.

**Comment by royalpranjal** [comment]
Here is the traceback

```
Traceback (most recent call last):
  File "/Users/royalpranjal/PycharmProjects/proj/proj/user/tests.py", line 133, in test_check_email
    temp_response = temp_client.post(url, data={'email': "abcd@gmail.com"})
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/rest_framework/test.py", line 290, in post
    path, data=data, format=format, content_type=content_type, **extra)
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/rest_framework/test.py", line 212, in post
    return self.generic('POST', path, data, content_type, **extra)
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/django/test/client.py", line 416, in generic
    return self.request(**r)
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/rest_framework/test.py", line 279, in request
    return super(APIClient, self).request(**kwargs)
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/rest_framework/test.py", line 231, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/django/test/client.py", line 501, in request
    six.reraise(*exc_info)
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/django/utils/six.py", line 686, in reraise
    raise value
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/django/template/response.py", line 107, in render
    self.content = self.rendered_content
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/rest_framework/renderers.py", line 703, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/rest_framework/renderers.py", line 636, in get_context
    raw_data_post_form = self.get_raw_data_form(data, view, 'POST', request)
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/rest_framework/renderers.py", line 552, in get_raw_data_form
    serializer = view.get_serializer()
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/rest_framework/generics.py", line 110, in get_serializer
    serializer_class = self.get_serializer_class()
  File "/Users/royalpranjal/PycharmProjects/proj/lib/python3.5/site-packages/rest_framework/generics.py", line 127, in get_serializer_class
    % self.__class__.__name__
AssertionError: 'CheckEmail' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
```
Here is the view 
```
class CheckEmail(CreateAPIView):
    permission_classes = [AllowAny]

    def create(self, request, *args, **kwargs):
        try:
            CommonValidations.validate_email(self.request.data.get('email'))
        except:
            return error_response(
                "That email address is already being used with another account, try a different one or log in")
        return Response(status=status.HTTP_200_OK)
```

Here is the test 
```
url = reverse('proj.check_email')
        temp_client = APIClient()

        temp_response = temp_client.post(url, data={'email': "abcd123@gmail.com", 'password': "password123"})
        self.assertEquals(temp_response.status_code, status.HTTP_200_OK)
```

**Comment by xordoquy** [comment]
That's because you're using the browsable API that introspects the view to add the forms. Definitively not an issue with the APIClient.

**Comment by royalpranjal** [comment]
probably late but thank you mate.
Not every hero wears a cape.
