### ISSUE TITLE
Adding -label argument to Snippet model causes ISE in Tutorial

### ISSUE THREAD

**Issue by stevepiercy** [encode/django-rest-framework#5573]
I'm not sure whether this is a bug, an issue in the tutorial, or an issue in documentation. I'm willing to provide a fix, once I know what is needed.

## Steps to reproduce
1. Follow instructions in [step 1 in tutorial](http://www.django-rest-framework.org/tutorial/1-serialization/) to the end.
2. Add the argument `label` to the `Snippet` model's field `linenos` in https://github.com/encode/django-rest-framework/blob/master/docs/tutorial/1-serialization.md#creating-a-model-to-work-with
    > linenos = models.BooleanField(default=False, label='Line Numbers')
3. Run the app.

## Expected behavior

I expected the field to display a label in [accordance with the documentation of field arguments](http://www.django-rest-framework.org/api-guide/fields/#label).

## Actual behavior

Internal Server Error. I had to remove the argument from my code, and restart the server to restore functionality.

**Comment by carltongibson** [comment]
@stevepiercy You need to paste the full traceback, otherwise we can't see what's going on. Thanks.

**Comment by stevepiercy** [comment]
```python
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x10d079268>
Traceback (most recent call last):
  File "/Users/stevepiercy/projects/rest-framework-tutorial-appa/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Users/stevepiercy/projects/rest-framework-tutorial-appa/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/Users/stevepiercy/projects/rest-framework-tutorial-appa/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/Users/stevepiercy/projects/rest-framework-tutorial-appa/env/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/stevepiercy/projects/rest-framework-tutorial-appa/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/Users/stevepiercy/projects/rest-framework-tutorial-appa/env/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/stevepiercy/projects/rest-framework-tutorial-appa/env/lib/python3.6/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models()
  File "/Users/stevepiercy/projects/rest-framework-tutorial-appa/env/lib/python3.6/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/Users/stevepiercy/.pyenv/versions/3.6.1/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/stevepiercy/projects/rest-framework-tutorial-appa/tutorial/snippets/models.py", line 13, in <module>
    class Snippet(models.Model):
  File "/Users/stevepiercy/projects/rest-framework-tutorial-appa/tutorial/snippets/models.py", line 17, in Snippet
    linenos = models.BooleanField(default=False, label='Line Numbers')
  File "/Users/stevepiercy/projects/rest-framework-tutorial-appa/env/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 996, in __init__
    super(BooleanField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'label'
```

**Comment by xordoquy** [comment]
The documentation refers to the Serializer's field, not Model's one.
Model's fields are part of Django. Their options are listed in the [documentation](https://docs.djangoproject.com/en/1.11/ref/models/fields/#field-options)

**Comment by stevepiercy** [comment]
OK, thanks for the pointer. FTR, adding this bit of code to `serializers.py` to the `SnippetSerializer` class has the effect I desired:

```
class SnippetSerializer(serializers.HyperlinkedModelSerializer):
    linenos = serializers.CharField(label='Line Numbers')
```
