### ISSUE TITLE
exceptions caused by format_suffix_patterns

### ISSUE THREAD

**Issue by CACppuccino** [encode/django-rest-framework#5628]
## Steps to reproduce
In django 1.10+, when coding the `urls.py` of the project file with the function `format_suffix_patterns`, an exception may occurred when dealing with the urlpatterns in a particular order.

this is the code of urls.py

```
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^zufang/', zufang_views.RentingRecords.as_view()),
    url(r'^ershou/', ershou_views.UsedItems.as_view()),
    url(r'^shunfengche/', include('shunfengche.urls', namespace='shunfengche')),
    url(r'^yp/', include('yellowpage.urls', namespace='yellowpage')),
    url(r'^bugs/', sfc_views.bugs), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns = format_suffix_patterns(urlpatterns)
urlpatterns.append(url(r'^users/', include('users.urls')))
urlpatterns.append(url(r'^courses/', include('courses.urls')))
urlpatterns.append(url(r'^official/', include('official.urls')))
urlpatterns.append(url(r'^', include('official.urls')))
```
when moving the formatting function to the bottom, like this:

```
urlpatterns.append(url(r'^users/', include('users.urls')))
urlpatterns.append(url(r'^courses/', include('courses.urls')))
urlpatterns.append(url(r'^official/', include('official.urls')))
urlpatterns.append(url(r'^', include('official.urls')))
urlpatterns = format_suffix_patterns(urlpatterns)

```
## Expected behavior
It was expected to be the same or throw an exception that is not confusing 
## Actual behavior
django throws two exceptions when performing the system checks

>Django version 1.11.2, using settings 'app.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Performing system checks...

>Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f282956d0d0>
Traceback (most recent call last):
  File "/root/pyenv/lib/python3.5/site-packages/django/urls/resolvers.py", line 105, in _compile
    return re.compile(regex, re.UNICODE)
  File "/root/pyenv/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/root/pyenv/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/root/pyenv/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/root/pyenv/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/root/pyenv/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/root/pyenv/lib/python3.5/sre_parse.py", line 774, in _parse
    raise source.error(err.msg, len(name) + 1) from None
sre_constants.error: redefinition of group name 'format' as group 2; was group 1 at position 32

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/root/pyenv/lib/python3.5/site-packages/django/utils/autoreload.py", line 227, in wrapper
    fn(*args, **kwargs)
  File "/root/pyenv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/root/pyenv/lib/python3.5/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/root/pyenv/lib/python3.5/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/root/pyenv/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/root/pyenv/lib/python3.5/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/root/pyenv/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/root/pyenv/lib/python3.5/site-packages/django/urls/resolvers.py", line 255, in check
    warnings.extend(check_resolver(pattern))
  File "/root/pyenv/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/root/pyenv/lib/python3.5/site-packages/django/urls/resolvers.py", line 255, in check
    warnings.extend(check_resolver(pattern))
  File "/root/pyenv/lib/python3.5/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/root/pyenv/lib/python3.5/site-packages/django/urls/resolvers.py", line 172, in check
    warnings = self._check_pattern_startswith_slash()
  File "/root/pyenv/lib/python3.5/site-packages/django/urls/resolvers.py", line 140, in _check_pattern_startswith_slash
    regex_pattern = self.regex.pattern
  File "/root/pyenv/lib/python3.5/site-packages/django/urls/resolvers.py", line 93, in __get__
    instance.__dict__['regex'] = self._compile(instance._regex)
  File "/root/pyenv/lib/python3.5/site-packages/django/urls/resolvers.py", line 109, in _compile
    (regex, six.text_type(e))
django.core.exceptions.ImproperlyConfigured: "^\.(?P<format>[a-z0-9]+)/?\.(?P<format>[a-z0-9]+)/?$" is not a valid regular expression: redefinition of group name 'format' as group 2; was group 1 at position 32

**Comment by xordoquy** [comment]
This is a very rare case -so far it's the first time I see it reported- and I'm more willing not to fix it to keep the code base simple enough.

**Comment by carltongibson** [comment]
I agree with @xordoquy here. That's just going to be a "Don't hold it that way" kind of issue. 

I'd happily review a PR adding a note to the docs, saying to `format_suffix_patterns` last, or such. 

At this stage, this isn't something I'm desperate to address. I'm inclined to close this on that basis, but I'll leave it open for the moment.

**Comment by scath999** [comment]
Wanted to report a similar (but not same) error with the current version of Django.

Could I *respectfully* suggest that Django flag offensive routes and output them to the console - or something similar? This was easy to fix, but I had to manually debug the problem by adding print statements to resolvers.py in order to find out what had gone wrong. The traceback didn't mention to any of my code until the very end, and even then only gave me the name of a variable that appears throughout my project, making it very difficult to understand where the problem was.

I should mention this is the first time I've worked with Django, and the first time I've worked on a full stack project since 2010.

Thanks for all your hard work.

**Comment by rpkilby** [comment]
Hi @scath999 👋  . I don't think we'd consider it an active issue, given limited maintainer bandwidth and the issue's rarity. That said, happy to review a PR that addresses it. Either a fix to the docs or the actual code (if not overly complicated).
