### ISSUE TITLE
django.db.transaction.TransactionManagementError when adding new token

### ISSUE THREAD

**Issue by tsantor** [encode/django-rest-framework#5859]
When trying to add a token via the Django admin at `/admin/authtoken/token/add/`, I get the following error:

    django.db.transaction.TransactionManagementError
    
    TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

This is with `django==1.11.2` and `djangorestframework==3.6.3`.

**UPDATE:** I have also tried this with `django==1.11.10` and `djangorestframework==3.7.7`.

**Comment by xordoquy** [comment]
It seems that some SQL request failed.
Unfortunately we can't do anything with the current issue unless. Maybe check the signals for a hint about why this fails.

**Comment by tsantor** [comment]
Ok, so I did a quick standalone test (a fresh project with no other apps installed) with only `django==1.11.10` and `djangorestframework==3.7.7` and this issue does not arise.  Why would adding a token through `rest_framework.authtoken` using the Django admin cause this when other apps are installed?

**Comment by xordoquy** [comment]
Some applications do some magic things behind your back which is why it may creates a nice first impression but leaves long hours of debug after that.
Alternatively, turn off atomic requests and see which query creates the issue. Traceback should help.

**Comment by tsantor** [comment]
Here is the stacktrace.  There are no mention of any 3rd party apps in here that are raising an exception.

I also added `DATABASES['default']['ATOMIC_REQUESTS'] = False` and the same thing occurs.

    Traceback (most recent call last):
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 66, in __call__
        return self.application(environ, start_response)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 146, in __call__
        response = self.get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 81, in get_response
        response = self._middleware_chain(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
        response = response_for_exception(request, exc)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
        response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
        return debug.technical_500_response(request, *exc_info)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
        six.reraise(exc_type, exc_value, tb)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/six.py", line 693, in reraise
        raise value
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
        response = get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
        response = self.get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
        response = response_for_exception(request, exc)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
        response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
        return debug.technical_500_response(request, *exc_info)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
        six.reraise(exc_type, exc_value, tb)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/six.py", line 693, in reraise
        raise value
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
        response = get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
        response = self.get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
        response = response_for_exception(request, exc)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
        response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
        return debug.technical_500_response(request, *exc_info)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
        six.reraise(exc_type, exc_value, tb)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/six.py", line 693, in reraise
        raise value
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
        response = get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
        response = self.get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
        response = response_for_exception(request, exc)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
        response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
        return debug.technical_500_response(request, *exc_info)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
        six.reraise(exc_type, exc_value, tb)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/six.py", line 693, in reraise
        raise value
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
        response = get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
        response = self.get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
        response = response_for_exception(request, exc)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
        response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
        return debug.technical_500_response(request, *exc_info)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
        six.reraise(exc_type, exc_value, tb)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/six.py", line 693, in reraise
        raise value
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
        response = get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
        response = self.get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
        response = response_for_exception(request, exc)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
        response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
        return debug.technical_500_response(request, *exc_info)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
        six.reraise(exc_type, exc_value, tb)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/six.py", line 693, in reraise
        raise value
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
        response = get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
        response = self.get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
        response = response_for_exception(request, exc)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
        response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
        return debug.technical_500_response(request, *exc_info)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
        six.reraise(exc_type, exc_value, tb)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/six.py", line 693, in reraise
        raise value
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
        response = get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
        response = self.get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
        response = response_for_exception(request, exc)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
        response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
        return debug.technical_500_response(request, *exc_info)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
        six.reraise(exc_type, exc_value, tb)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/six.py", line 693, in reraise
        raise value
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
        response = get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
        response = self.get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
        response = response_for_exception(request, exc)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
        response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
        return debug.technical_500_response(request, *exc_info)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
        six.reraise(exc_type, exc_value, tb)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/six.py", line 693, in reraise
        raise value
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
        response = get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/easyaudit/middleware/easyaudit.py", line 49, in __call__
        return self.get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
        response = response_for_exception(request, exc)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
        response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
        return debug.technical_500_response(request, *exc_info)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
        six.reraise(exc_type, exc_value, tb)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/six.py", line 693, in reraise
        raise value
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
        response = get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/utils/deprecation.py", line 95, in __call__
        response = self.get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 37, in inner
        response = response_for_exception(request, exc)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 87, in response_for_exception
        response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 122, in handle_uncaught_exception
        return debug.technical_500_response(request, *exc_info)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
        six.reraise(exc_type, exc_value, tb)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/six.py", line 693, in reraise
        raise value
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
        response = get_response(request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
        response = self.process_exception_by_middleware(e, request)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 574, in wrapper
        return self.admin_site.admin_view(view)(*args, **kwargs)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
        response = view_func(request, *args, **kwargs)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
        response = view_func(request, *args, **kwargs)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 223, in inner
        return view(request, *args, **kwargs)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1553, in add_view
        return self.changeform_view(request, None, form_url, extra_context)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/utils/decorators.py", line 62, in _wrapper
        return bound_func(*args, **kwargs)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
        response = view_func(request, *args, **kwargs)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/utils/decorators.py", line 58, in bound_func
        return func.__get__(self, type(self))(*args2, **kwargs2)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1450, in changeform_view
        return self._changeform_view(request, object_id, form_url, extra_context)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1494, in _changeform_view
        self.log_addition(request, new_object, change_message)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/contrib/admin/options.py", line 773, in log_addition
        change_message=message,
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/contrib/admin/models.py", line 29, in log_action
        change_message=change_message,
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/db/models/query.py", line 417, in create
        obj.save(force_insert=True, using=self.db)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/db/models/base.py", line 729, in save
        force_update=force_update, update_fields=update_fields)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/db/models/base.py", line 759, in save_base
        updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/db/models/base.py", line 842, in _save_table
        result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/db/models/base.py", line 880, in _do_insert
        using=using, raw=raw)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
        return getattr(self.get_queryset(), name)(*args, **kwargs)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/db/models/query.py", line 1125, in _insert
        return query.get_compiler(using=using).execute_sql(return_id)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1281, in execute_sql
        cursor.execute(sql, params)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/debug_toolbar/panels/sql/tracking.py", line 164, in execute
        return self._record(self.cursor.execute, sql, params)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/debug_toolbar/panels/sql/tracking.py", line 106, in _record
        return method(sql, params)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
        return super().execute(sql, params)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
        return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
        return executor(sql, params, many, context)
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/db/backends/utils.py", line 80, in _execute
        self.db.validate_no_broken_transaction()
    File "/Users/tsantor/.virtualenvs/myproject_env/lib/python3.6/site-packages/django/db/backends/base/base.py", line 437, in validate_no_broken_transaction
        "An error occurred in the current transaction. You can't "
    django.db.transaction.TransactionManagementError: An error occurred in the current transaction. You can't execute queries until the end of the 'atomic' block.

**Comment by tsantor** [comment]
For anyone that may ever come across the same issue. This issue only happens if you have `django-easy-audit` installed and `easyaudit` in your `INSTALLED_APPS`. Remove the offending 3rd party app and the problem goes away.
