### ISSUE TITLE
detail_route/list_route doesn't allow to disable schema generation

### ISSUE THREAD

**Issue by ola-t** [encode/django-rest-framework#5995]
Would be nice if `detail_route` or `list_route` woudl allow to disable schema generation
by setting arg `schema=None`. 

```
    @detail_route(
        methods=['get', ],
        schema=None,
        ...
    )
```

At the moment I have to build separate view

```
class MyViewSet(mixins.ListModelMixin, viewsets.GenericViewSet):
    ...
    schema = None
    ...
```

**Comment by rpkilby** [comment]
Hi @ola-t. Could you check to see if #5992 fixes your issue?

**Comment by ola-t** [comment]
I am getting the same error:

```
Traceback (most recent call last):
  File "/opt/venv/py36_django/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/opt/venv/py36_django/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/venv/py36_django/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/venv/py36_django/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/venv/py36_django/lib/python3.6/site-packages/rest_framework/viewsets.py", line 83, in view
    self = cls(**initkwargs)
  File "/opt/venv/py36_django/lib/python3.6/site-packages/django/views/generic/base.py", line 44, in __init__
    setattr(self, key, value)
  File "/opt/venv/py36_django/lib/python3.6/site-packages/rest_framework/schemas/inspectors.py", line 160, in __set__
    other.view = instance
AttributeError: 'NoneType' object has no attribute 'view'
```

**Comment by rpkilby** [comment]
Hi @ola-t. I've updated the PR. How about now?
