### ISSUE TITLE
3.9: AttributeError when Schema Endpoint requires authentication

### ISSUE THREAD

**Issue by bpereto** [encode/django-rest-framework#6258]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
* Update to 3.9
* Implement Schema Endpoint as described in Announcement: https://www.django-rest-framework.org/community/3.9-announcement/
```
from rest_framework.schemas import get_schema_view

schema_view = get_schema_view(
    title='Server Monitoring API',
    url='https://www.example.org/api/'
)

urlpatterns = [
    url('^schema.json$', schema_view),
]
```
* Set Permission `IsAuthenticated`:
```
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
```
* Open `/schema.json`

## Expected behavior
* Authorization Error

## Actual behavior
```
Internal Server Error: /schema.json
Traceback (most recent call last):
  File "./.venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "./.venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "./.venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "./.venv/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "./.venv/lib/python3.6/site-packages/rest_framework/response.py", line 72, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "./.venv/lib/python3.6/site-packages/rest_framework/renderers.py", line 732, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "./.venv/lib/python3.6/site-packages/rest_framework/renderers.py", line 687, in get_context
    'content': self.get_content(renderer, data, accepted_media_type, renderer_context),
  File "./.venv/lib/python3.6/site-packages/rest_framework/renderers.py", line 423, in get_content
    content = renderer.render(data, accepted_media_type, renderer_context)
  File "./.venv/lib/python3.6/site-packages/rest_framework/renderers.py", line 1036, in render
    structure = self.get_structure(data)
  File "./.venv/lib/python3.6/site-packages/rest_framework/renderers.py", line 1016, in get_structure
    'title': data.title,
AttributeError: 'dict' object has no attribute 'title'
```

```
.venv/lib/python3.6/site-packages/rest_framework/renderers.py in get_structure
data = {'detail': ErrorDetail(string='Authentication credentials were not provided.', code='not_authenticated')}

```

**Comment by thePaulKelley** [comment]
I'm having the same issue.

**Comment by rpkilby** [comment]
Thanks for the minimal reproduction and traceback.

cc @carltongibson?

**Comment by carltongibson** [comment]
OK, so yes... 

This looks to me like a variant of the same issue that came up with 3.6, when we introduced the interactive docs. Basically (I guess) the schema view is picking up `DEFAULT_AUTHENTICATION_CLASSES`. See e.g. #5399, #5309, #5448...

`get_schema_view()` takes `authentication_classes`. First this would be to try passing an empty list in there... 

(Does that help?)

**Comment by carltongibson** [comment]
Is this a duplicate of #6258?

**Comment by carltongibson** [comment]
> ... this is #6258 😄

Thought it looked relevant. 

> Brough you this ☕️

Thanks!

**Comment by devsnd** [comment]
For those that are stuck here, you can just pass the `AllowAny` permission to the `schema_view` as a workaround.

    schema_view = get_schema_view(
        title="My API",
        permission_classes=[rest_framework.permissions.AllowAny],
    )

**Comment by shapiromatron** [comment]
FYI, I'm still stuck here. I have a custom permission class that doesn't require authentication, so the workaround proposed by @devsnd doesn't work for me
