### ISSUE TITLE
OpenApi Schema Generator does not expose all parameters on ViewSet

### ISSUE THREAD

**Issue by bpereto** [encode/django-rest-framework#6260]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
* enable openapi renderer with release 3.9
* Use a simple ViewSet

## Expected behavior
* OpenAPI Schema exposes needed parameter for Object creation (ex. POST on `/thing`)

## Actual behavior
* Client error with `apistar`
* DRF Schema Generator does not expose needed parameters
```
Traceback (most recent call last):
  File "apistarclient.py", line 99, in <module>
    apistr.request('thing_create', name='asdfiiiii')
  File "./.venv/lib/python3.6/site-packages/apistar/client/client.py", line 85, in request
    raise exceptions.ClientError(messages=exc.messages) from None
apistar.exceptions.ClientError: [ErrorMessage('Invalid property name.', code='invalid_property', index=['name'], position=None)]
```

Seems to be an error on https://github.com/encode/django-rest-framework/blob/master/rest_framework/renderers.py#L960
the `field.location` is `form` and skipped.

### Schema
```
info:
  description: ''
  title: Things API
  version: ''
openapi: 3.0.0
paths:
  /thing/:
    get:
      description: 'API endpoint that allows Thing instances

        to be viewed or edited.'
      operationId: thing_list
      tags:
      - thing
    post:
      description: 'API endpoint that allows Thing instances

        to be viewed or edited.'
      operationId: thing_create
      parameters:
      - in: path
        name: name
        required: true
        schema:
          description: ''
          title: Name
          type: string
      tags:
      - thing
  /thing/{id}/:
    delete:
      description: 'API endpoint that allows Thing instances

        to be viewed or edited.'
      operationId: thing_delete
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this thing.
          title: ID
          type: integer
      tags:
      - thing
    get:
      description: 'API endpoint that allows Thing instances

        to be viewed or edited.'
      operationId: thing_read
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this thing.
          title: ID
          type: integer
      tags:
      - thing
    patch:
      description: 'API endpoint that allows Thing instances

        to be viewed or edited.'
      operationId: thing_partial_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this thing.
          title: ID
          type: integer
      - in: path
        name: name
        schema:
          description: ''
          title: Name
          type: string
      tags:
      - thing
    put:
      description: 'API endpoint that allows Thing instances

        to be viewed or edited.'
      operationId: thing_update
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this thing.
          title: ID
          type: integer
      - in: path
        name: name
        required: true
        schema:
          description: ''
          title: Name
          type: string
      tags:
      - thing
  /thing/{id}/ding/:
    get:
      description: 'API endpoint that allows Thing instances

        to be viewed or edited.'
      operationId: thing_ding
      parameters:
      - in: path
        name: id
        required: true
        schema:
          description: A unique integer value identifying this thing.
          title: ID
          type: integer
      tags:
      - thing
servers:
- url: http://localhost:8000/schema
```

**Comment by illing2005** [comment]
Adding `form` to `field.location` does not solve the issue. 
When I do this and try to serve the docs with apistar, I get the following error message:
`Must be one of ['query', 'header', 'path', 'cookie']. (At ['paths', '/api/search-requests/', 'post', 'parameters', 11, 'in'], line 804, column 13.)`

**Comment by illing2005** [comment]
Any updates on this issue?

**Comment by carltongibson** [comment]
Hi @illing2005: if there were, there'd be more comments 😀. 

It's kind of mentioned in the 3.9 release notes, but, we're migrating from the existing CoreAPI based schema generation to a straight-to-OpenAPI approach. The main changed here will be in place for v3.10. After that we'll be in a position to improve the details of schema generation, and **importantly** take more input from users. 

Right now you may have to enhance the generated schema to get the exact results you need.

**Comment by illing2005** [comment]
Thanks for the clarification, @carltongibson!
As the default schema renderer changed to `OpenAPIRenderer` in 3.9, I thought it was ready to use. 
Do you already know approximatly when 3.10 will be released?

**Comment by carltongibson** [comment]
It is. That there are limitations is just called software. ≈April.

**Comment by browniebroke** [comment]
I'm going to assume that this issue is about the built-in, deprecated, [OpenAPI schema generator](https://www.django-rest-framework.org/topics/documenting-your-api/#built-in-openapi-schema-generation-deprecated) and I'm going to close it. Let me know if I'm missing anything.
