### ISSUE TITLE
Syntax Error on 0002 of rest_framework.authtoken migration with django 2.1.2

### ISSUE THREAD

**Issue by kasaiee** [encode/django-rest-framework#6357]
hello, when I tried to run `python manage.py migrate` for the first time, I got this error log:

```
Applying authtoken.0001_initial... OK
  Applying authtoken.0002_auto_20160226_1747...Traceback (most recent call last):
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: syntax error at or near "WITH ORDINALITY"
LINE 6:                     FROM unnest(c.conkey) WITH ORDINALITY co...
                                                  ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/core/management/commands/migrate.py", line 203, in handle
    fake_initial=fake_initial,
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 117, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 147, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/migrations/migration.py", line 124, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/migrations/operations/fields.py", line 216, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 523, in alter_field
    old_db_params, new_db_params, strict)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/backends/postgresql/schema.py", line 122, in _alter_field
    new_db_params, strict,
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 531, in _alter_field
    fk_names = self._constraint_names(model, [old_field.column], foreign_key=True)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/backends/base/schema.py", line 1029, in _constraint_names
    constraints = self.connection.introspection.get_constraints(cursor, model._meta.db_table)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/backends/postgresql/introspection.py", line 158, in get_constraints
    """, ["public", table_name])
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/safarbecom/env/lib64/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: syntax error at or near "WITH ORDINALITY"
LINE 6:                     FROM unnest(c.conkey) WITH ORDINALITY co...
                                                  ^
```

at last, I downgrade the version of django to 2 by `pip install django==2` and problem solved.

**Comment by xordoquy** [comment]
looks like you have a postgresql that is incompatible with Django 2.1 (ie older than 9.4).

**Comment by colegatron** [comment]
No workaround possible? Can't upgrade this postgres now :-(

**Comment by colegatron** [comment]
Meh. that's a dilemma... go back to Django 2.0 vs update PostgreSQL 9.3 to 9.6.
Ideally, none of the options should be a problem, but the reality is though. 

Tnx @xordoquy

**Comment by hathucphuc** [comment]
Hi everybody,
I am using django 2.24 and postgres 9.2 . So i just need downgrate django to 2.0? Il will solve?
It's too hard to upgrate database in my project
thanks

**Comment by xordoquy** [comment]
@hathucphuc this isn't a support forum. You should ask that on the [Django user mailing list](https://docs.djangoproject.com/en/dev/internals/mailing-lists/#django-users) because it's a Django related question
