### ISSUE TITLE
Crash when running generateschema

### ISSUE THREAD

**Issue by aleksanb** [encode/django-rest-framework#6553]
Spun out from https://github.com/encode/django-rest-framework/pull/6532#issuecomment-478374167.

I did a quick test locally on our project which uses django_fields amongst other things. I added
```
    def get_schema_operation_parameters(self, view):
        return [] 
```
to DjangoFilterSetBackend as suggested, and hit a new issue with generating the schema:
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/Users/.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/rest_framework/management/commands/generateschema.py", line 24, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/Users/.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/rest_framework/schemas/generators.py", line 519, in get_schema
    paths = self.get_paths(None if public else request)
  File "/Users/.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/rest_framework/schemas/generators.py", line 506, in get_paths
    operation = view.schema.get_operation(path, method)
  File "/Users/.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/rest_framework/schemas/inspectors.py", line 536, in get_operation
    operation['responses'] = self._get_responses(path, method)
  File "/Users/.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/rest_framework/schemas/inspectors.py", line 791, in _get_responses
    content = self._map_serializer(serializer)
  File "/Users/.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/rest_framework/schemas/inspectors.py", line 728, in _map_serializer
    schema = self._map_field(field)
  File "/Users/.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/rest_framework/schemas/inspectors.py", line 655, in _map_field
    'items': self._map_serializer(field.child)
  File "/Users/.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/rest_framework/schemas/inspectors.py", line 721, in _map_serializer
    for field in serializer.fields.values():
AttributeError: 'DateTimeRangeField' object has no attribute 'fields'
```

so it might have issues with from drf_extra_fields.fields import DateTimeRangeField? Do custom fields need new attributes?

It could be related to our homebrewn permission system which returns different types of serializers from get_serializer dependent on the request user and which object you're trying to access, but that's a wild guess as I haven't looked into the schema generation code that's crashing as of yet.

**Comment by Lucidiot** [comment]
Hi @aleksanb! The `get_serializer` method is called without a request when using `manage.py generateschema` and with a request if the schema generation uses a dynamic endpoint [as described here](https://www.django-rest-framework.org/api-guide/schemas/#adding-a-schema-view), but I do not think returning different serializers is the main problem if there is a default serializer when there are no requests.

From what I gather, it seems an API view returned a serializer that has a field that looked like a nested [list serializer](https://www.django-rest-framework.org/api-guide/serializers/#listserializer), and ran `_map_serializer` on its child, a `DateTimeRangeField`. I believe replacing the call to `_map_serializer` with a call to `_map_field` [here](https://github.com/encode/django-rest-framework/blob/fa40bfa278ceae3053f6d74854e935fb333c998a/rest_framework/schemas/inspectors.py#L655) would fix the problem, but you may want to try checking whether you are using a list *serializer* with a *field* as its child. You should use a [`ListField`](https://www.django-rest-framework.org/api-guide/fields/#listfield) to represent N times the same field, and use a serializer with `many=True` to represent N times the same serializer.

**Comment by aleksanb** [comment]
That was spot on, it went on trucking when i switched to ListFields, and crashed at something new instead! I tried reading the linked documentation, but i'm still confused as to what the difference was between ListField and ListSerializer. Am i supposd to use ListField if nested within another serializer, and ListSerializer if it's the outermost serializer?

Next error:
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users//.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users//.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users//.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users//.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/Users//.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/rest_framework/management/commands/generateschema.py", line 24, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/Users//.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/rest_framework/schemas/generators.py", line 519, in get_schema
    paths = self.get_paths(None if public else request)
  File "/Users//.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/rest_framework/schemas/generators.py", line 506, in get_paths
    operation = view.schema.get_operation(path, method)
  File "/Users//.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/rest_framework/schemas/inspectors.py", line 525, in get_operation
    operation['operationId'] = self._get_operation_id(path, method)
  File "/Users//.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/rest_framework/schemas/inspectors.py", line 560, in _get_operation_id
    name = self.view.get_serializer_class().__name__
  File "/Users//.local/share/virtualenvs/app-SIjAPd74/lib/python3.7/site-packages/rest_framework/generics.py", line 127, in get_serializer_class
    % self.__class__.__name__
AssertionError: 'CreditCardViewSet' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.
```

This is in a
```
class CreditCardViewSet(PermissionMixin, viewsets.GenericViewSet):
    object_permissions = CreditCardPermission
    pagination_class = None

... other stuff
```
where PermissionMixin defines get_serializer only.

**Comment by Lucidiot** [comment]
Here's a *great* example:

``` python
class AGreatSerializer(serializers.Serializer):
    moar_text = serializers.CharField()
    a_list = serializers.ListField(serializers.IntegerField())

class AnotherGreatSerializer(serializers.Serializer):
    some_text = serializers.CharField()
    nested = AGreatSerializer(many=True)
```

Using the above serializers could give you this kind of JSON:

``` json
{
    "some_text": "Hello, world",
    "nested": [
        {
            "moar_text": "Lorem ipsum",
            "a_list": [1, 2, 3],
        },
        {
            "moar_text": "Another one!",
            "a_list": [4, 5, 6],
        },
    ],
}
```

A `ListField` gives you the ability to represent 0 to N times a single Field, using... a list. A `ListSerializer` is pretty much a `ListField`, but for a Serializer. You would usually not use a `ListSerializer` directly in normal situations; you would use a normal serializer with the `many=True` parameter instead.

As for your next error, this comes from the small and very simple implementation I wrote for the `operationId` generator; I already have a bunch of edits to make on it, so I will work on that as soon as I can. Thanks for the heads up!

**Comment by carltongibson** [comment]
Yep, the key point here is this one: `AGreatSerializer(many=True)` — for a nested serializer you use the `many=True` option and DRF takes care of switching in a `ListSerializer` for you. 

I'm going to assume adjusting corrects the error here. **IF NOT** come back and we can look again.
