### ISSUE TITLE
Exceptions stack trace are truncated since 3.9.3

### ISSUE THREAD

**Issue by antwan** [encode/django-rest-framework#6655]
Since introduction of change #6435 (commit fd32dd7), exceptions that are raised within a DRF `APIView` have their stack trace truncated. It is therefore very difficult to fix issues as there is no longer indication of line number/file affected when exception is uncaught.

## Steps to reproduce

1. Create a simple view in your code to trigger an uncaught exception

```
# views.py
from rest_framework.views import APIView

class CrashView(APIView):
    def get(self, request):
        raise Exception('A test exception occured!')
```

```
# urls.py
from django.conf.urls import url
from .views import CrashView

urlpatterns = [
    url(r'^crash-me/$', CrashView.as_view(), name='crash-me'),
]
```

2. Call the view
`GET /crash-me/`

## Expected behavior

Stack trace returned should be the following:

```
Traceback (most recent call last):
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/Users/antwan/Projects/drf-bug/views.py", line 5, in get
    raise Exception('A test exception occured!')
```

## Actual behavior

Stack trace returned is the following:

```
Traceback (most recent call last):
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/antwan/Projects/venv/lib/python2.7/site-packages/rest_framework/views.py", line 466, in raise_uncaught_exception
    raise exc
```

**Comment by rpkilby** [comment]
Interesting. From my test in  https://github.com/encode/django-rest-framework/pull/6435#issuecomment-468846050, there didn't seem to be a significant behavior change. Are you using Python 2 or Python 3?

**Comment by rpkilby** [comment]
Agh. Confirmed. The change is fine on Python 3, but negatively affects Python 2 error handling.

**Comment by antwan** [comment]
> ref #6404
> Although, knowing my luck, this _will_ break something.

Bingo 😬

**Comment by rpkilby** [comment]
Can you roll back to 3.9.2? iirc, the only meaningful change was #6613 - the rest being docs/test fixes.

**Comment by rpkilby** [comment]
At this point, we're already in the process of rolling 3.10, which drops Python 2 support entirely.

**Comment by antwan** [comment]
Of course I've rolled back to 3.9.2, but that's definitely not an answer.

I don't see why we should leave a version on prod with rather serious bugs IMO. This should be fixed for the the time being (ie as long as 3.9 series is supported). I'm certainly not the only one affected here.
All the more #6404 does not bring a lot TBH.

**Comment by xordoquy** [comment]
I don't consider this issue as serious although it definitively is really annoying.
As said, Python 2 has already been dropped so it's quite some extra work to issue a 3.9.4.
We need to see whether the best option is to deactivate 3.9.3 from pypi or to issue another release.

**Comment by rpkilby** [comment]
It shouldn't be *too* difficult. 
- create a `3.9.x` branch
- rollback the fix
- create new release

The question is whether or not @carltongibson has the bandwidth to run through this. I don't want to volunteer/obligate him to work if he doesn't have the time.

**Comment by carltongibson** [comment]
If you can create the tag Ryan I am happy to push it to PyPI

**Comment by rpkilby** [comment]
👌

**Comment by rpkilby** [comment]
@carltongibson 3.9.4 is up https://github.com/encode/django-rest-framework/compare/3.9.3...3.9.4

**Comment by rpkilby** [comment]
Also, there is a 3.9.x brach if we need to make any additional maintenance updates.

**Comment by carltongibson** [comment]
OK. Super I’ll push that now. Thanks!
