### ISSUE TITLE
Pagination broken

### ISSUE THREAD

**Issue by VerySmallSnake** [encode/django-rest-framework#6973]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

```
Traceback (most recent call last):
  File "/home/user/VirtualEnvironments/venv1/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/user/VirtualEnvironments/venv1/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/user/VirtualEnvironments/venv1/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/VirtualEnvironments/venv1/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/user/VirtualEnvironments/venv1/lib/python3.7/site-packages/rest_framework/viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/VirtualEnvironments/venv1/lib/python3.7/site-packages/rest_framework/views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "/home/user/VirtualEnvironments/venv1/lib/python3.7/site-packages/rest_framework/views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/user/VirtualEnvironments/venv1/lib/python3.7/site-packages/rest_framework/views.py", line 468, in raise_uncaught_exception
    raise exc
  File "/home/user/VirtualEnvironments/venv1/lib/python3.7/site-packages/rest_framework/views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/user/VirtualEnvironments/venv1/lib/python3.7/site-packages/rest_framework/mixins.py", line 40, in list
    page = self.paginate_queryset(queryset)
  File "/home/user/VirtualEnvironments/venv1/lib/python3.7/site-packages/rest_framework/generics.py", line 171, in paginate_queryset
    return self.paginator.paginate_queryset(queryset, self.request, view=self)
  File "/home/user/VirtualEnvironments/venv1/lib/python3.7/site-packages/rest_framework/pagination.py", line 203, in paginate_queryset
    self.page = paginator.page(page_number)
  File "/home/user/VirtualEnvironments/venv1/lib/python3.7/site-packages/django/core/paginator.py", line 75, in page
    return self._get_page(self.object_list[bottom:top], number, self)
TypeError: 'RelatedManager' object is not subscriptable
```

## Steps to reproduce
Include 
```
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100
}
```
in settings.py

## Expected behavior
No such errors

## Actual behavior
Error

**Comment by PUYUP** [comment]
Please inform your queryset objects. Maybe something wrong in there.

**Comment by xordoquy** [comment]
This looks like a usage issue.
Seems you are providing a `Manager` instead of a `QuerySet` to the pagination.
Dont forget to call `all()`.
