### ISSUE TITLE
SchemaGenerator exceptions

### ISSUE THREAD

**Issue by DanLipsitt** [encode/django-rest-framework#7025]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

```shellsession
$ ./src/manage.py shell -c 'from rest_framework.schemas.openapi import SchemaGenerator; SchemaGenerator(title="api").get_paths()'
Traceback (most recent call last):
  File "./src/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dan/.virtualenvs/cloud-hcs-xx7P09kR/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/dan/.virtualenvs/cloud-hcs-xx7P09kR/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dan/.virtualenvs/cloud-hcs-xx7P09kR/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dan/.virtualenvs/cloud-hcs-xx7P09kR/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/dan/.virtualenvs/cloud-hcs-xx7P09kR/lib/python3.7/site-packages/django/core/management/commands/shell.py", line 86, in handle
    exec(options['command'])
  File "<string>", line 1, in <module>
  File "/Users/dan/.virtualenvs/cloud-hcs-xx7P09kR/lib/python3.7/site-packages/rest_framework/schemas/openapi.py", line 38, in get_paths
    paths, view_endpoints = self._get_paths_and_endpoints(request)
  File "/Users/dan/.virtualenvs/cloud-hcs-xx7P09kR/lib/python3.7/site-packages/rest_framework/schemas/generators.py", line 179, in _get_paths_and_endpoints
    for path, method, callback in self.endpoints:
TypeError: 'NoneType' object is not iterable
```

```shellsession
$ ./src/manage.py shell -c 'from rest_framework.schemas.openapi import SchemaGenerator; SchemaGenerator(title="api").get_schema()'
Traceback (most recent call last):
  File "./src/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/dan/.virtualenvs/cloud-hcs-xx7P09kR/lib/python3.7/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/Users/dan/.virtualenvs/cloud-hcs-xx7P09kR/lib/python3.7/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/dan/.virtualenvs/cloud-hcs-xx7P09kR/lib/python3.7/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/dan/.virtualenvs/cloud-hcs-xx7P09kR/lib/python3.7/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/Users/dan/.virtualenvs/cloud-hcs-xx7P09kR/lib/python3.7/site-packages/django/core/management/commands/shell.py", line 86, in handle
    exec(options['command'])
  File "<string>", line 1, in <module>
  File "/Users/dan/.virtualenvs/cloud-hcs-xx7P09kR/lib/python3.7/site-packages/rest_framework/schemas/openapi.py", line 64, in get_schema
    paths = self.get_paths(None if public else request)
  File "/Users/dan/.virtualenvs/cloud-hcs-xx7P09kR/lib/python3.7/site-packages/rest_framework/schemas/openapi.py", line 47, in get_paths
    operation = view.schema.get_operation(path, method)
AttributeError: 'AutoSchema' object has no attribute 'get_operation'
```

**Comment by DanLipsitt** [comment]
More info. From my reading of the code, it doesn't seem like `coreapi` should be used if `DEFAULT_SCHEMA_CLASS` is `rest_framework.schemas.AutoSchema`, but it is:

```
ipdb> django.__version__
'2.2.6'
ipdb> rest_framework.__version__
'3.10.3'
ipdb> where
  <ipython-input-5-4a9288351321>(1)<module>()
----> 1 generator.get_schema()

  python3.7/site-packages/rest_framework/schemas/openapi.py(64)get_schema()
     62         self._initialise_endpoints()
     63
---> 64         paths = self.get_paths(None if public else request)
     65         if not paths:
     66             return None

> python3.7/site-packages/rest_framework/schemas/openapi.py(47)get_paths()
     45             if not self.has_view_permissions(path, method, view):
     46                 continue
---> 47             operation = view.schema.get_operation(path, method)
     48             # Normalise path for any provided mount url.
     49             if path.startswith('/'):
ipdb> settings.REST_FRAMEWORK['DEFAULT_SCHEMA_CLASS']
'rest_framework.schemas.AutoSchema'
ipdb> view.schema
<rest_framework.schemas.coreapi.AutoSchema object at 0x112cc2f10>
```

**Comment by realitix** [comment]
Hello,

I got a similar error when trying to generate the schema:

```
'ManualSchema' object has no attribute 'get_operation'
```

**Comment by carltongibson** [comment]
If you're using `ManualSchema` you're still in `CoreAPI` land. 

See [Continuing to use CoreAPI](https://www.django-rest-framework.org/community/3.10-announcement/#continuing-to-use-coreapI) from the 3.10 release announcement.
