### ISSUE TITLE
SearchFilter docs for full-text search are outdated

### ISSUE THREAD

**Issue by baphuc1998** [encode/django-rest-framework#7033]
The `SearchFilter` states that full-text search is only supported for MySQL. 

> '@' Full-text search. (Currently only supported Django's MySQL backend.)

However, this is no longer true.
- Django 1.10 added full-text search support for Postgres
- Django 2.0 dropped full-text search support for MySQL
    - However, it's trivial to re-add it ([link](https://docs.djangoproject.com/en/2.2/releases/1.10/#search-query-lookup)).  

----

<details>

<summary>Original issue:</summary>

I can not use Full-text search in my app. I used Mysql according to the instructions of the document.
How can I solve it? Thanks in advance ^^

Python: 3.7.3
djangorestframework: 3.10.2
Django: 2.2.4
django-filter: 2.2.0

Error:
```python
Traceback (most recent call last):
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)  
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 457, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 468, in raise_uncaught_exception
    raise exc
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\views.py", line 494, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\generics.py", line 199, in get
    return self.list(request, *args, **kwargs)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\generics.py", line 150, in filter_queryset
    queryset = backend().filter_queryset(self.request, queryset, self)       
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\rest_framework\filters.py", line 122, in filter_queryset
    queryset = queryset.filter(reduce(operator.and_, conditions))
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\sql\query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\sql\query.py", line 1312, in _add_q
    current_negated, allow_joins, split_subq, simple_col)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\sql\query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\sql\query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\sql\query.py", line 1110, in build_lookup
    lhs = self.try_transform(lhs, lookup_name)
  File "C:\Users\ilove\AppData\Local\Programs\Python\Python37\lib\site-packages\django\db\models\sql\query.py", line 1151, in try_transform
    "permitted%s" % (name, output_field.__name__, suggestion)
django.core.exceptions.FieldError: Unsupported lookup 'search' for CharField 
or join on the field not permitted.
```

</details>

**Comment by rpkilby** [comment]
Hi @baphuc1998. Django 2.0 removed the default `search` lookup for MySQL. If you want to reenable it, you'll need to create a lookup. 

See: https://docs.djangoproject.com/en/2.2/releases/1.10/#search-query-lookup

**Comment by rpkilby** [comment]
Reopening to track necessary documentation changes.
