### ISSUE TITLE
AttributeError: 'WSGIRequest' object has no attribute 'auth'

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [encode/django-rest-framework#7210]
When using Token based authentication I fetched token with apiView and then when a request is made with the token the user in `request.user` is `AnonymousUser` and the `request.auth` throws error `AttributeError: 'WSGIRequest' object has no attribute 'auth'` 

```
Environment:


Request Method: GET
Request URL: http://127.0.0.1:8000/planter/testlogin

Django Version: 3.0.3
Python Version: 3.6.9
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'planter.apps.PlanterConfig',
 'graphene_django',
 'rest_framework.authtoken']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/home/a-c-sreedhar-reddy/Desktop/plant/venv/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/a-c-sreedhar-reddy/Desktop/plant/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/a-c-sreedhar-reddy/Desktop/plant/venv/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/a-c-sreedhar-reddy/Desktop/plant/planter/views.py", line 36, in testlogin
    print(request.auth)

Exception Type: AttributeError at /planter/testlogin
Exception Value: 'WSGIRequest' object has no attribute 'auth'
```

**Comment by tomchristie** [comment]
The `request.auth` property is only available within REST framework views.
It looks like you're attempting to access it inside a standard Django view.

**Comment by a-c-sreedhar-reddy** [comment]
Is it the same case with `request.user` ?

**Comment by xkyang1** [comment]
help , the error log is below :

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.9/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/contrib/staticfiles/handlers.py", line 81, in __call__
    return super().__call__(environ, start_response)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/core/handlers/wsgi.py", line 124, in __call__
    response = self.get_response(request)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/contrib/staticfiles/handlers.py", line 56, in get_response
    return response_for_exception(request, e)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 68, in response_for_exception
    response = get_exception_response(
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 167, in get_exception_response
    response = handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/core/handlers/exception.py", line 185, in handle_uncaught_exception
    return callback(request)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/software/Archery-v1.10.0/common/views.py", line 38, in server_error
    return HttpResponseServerError(render(request, template_name))
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/template/base.py", line 173, in render
    with context.bind_template(self):
  File "/usr/local/python3/lib/python3.9/contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "/software/Python-3.9.10/venv4archery/lib/python3.9/site-packages/django/template/context.py", line 254, in bind_template
    updates.update(processor(self.request))
  File "/software/Archery-v1.10.0/common/utils/global_info.py", line 10, in global_info
    user = request.user
AttributeError: 'WSGIRequest' object has no attribute 'user'

**Comment by xkyang1** [comment]
Can someone help me analyze what the problem ？thk .
