### ISSUE TITLE
NotImplementedError with no details

### ISSUE THREAD

**Issue by crimsonpython24** [encode/django-rest-framework#7422]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Fairly easy to start. Just create a new Django application, register it in the settings.py file, and then this is good to go (I mean run-able). My problem started with these files: `djangorestframework == 3.11.0`
*serializers.py*
```python
from rest_framework import serializers

class TodoSerializer(serializers.BaseSerializer):
    level_choices = [
        ('important', 'Important'),
        ('normal', 'Normal'),
        ('unimportant', 'Not important')
    ]
    title = serializers.CharField(max_length=150, trim_whitespace=True)
    desc = serializers.CharField(max_length=500, allow_blank=True)
    level = serializers.ChoiceField(choices=level_choices)
    created = serializers.DateTimeField()
```
*urls.py*
```python
from django.urls import path, include
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'todos', views.TodoViewSet)
urlpatterns = [
    path('api/', include(router.urls)),
]
```
*views*
```python
from rest_framework import viewsets
from .models import Todo
from .serializers import TodoSerializer

class TodoViewSet(viewsets.ModelViewSet):
    queryset = Todo.objects.all()
    serializer_class = TodoSerializer
```
*settings.py*
```python
INSTALLED_APPS = [
    'rest_framework',
]

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}
```
## Expected behavior
Something like this with all the data of the todos, but with the styles and all the things applied.
![image](https://user-images.githubusercontent.com/56590830/87946744-00e3df00-cad5-11ea-9276-efd249d5619d.png)

## Actual behavior
Not working.
![image](https://user-images.githubusercontent.com/56590830/87946814-1822cc80-cad5-11ea-945e-ba07976d858b.png)

```bash
Internal Server Error: /todo/api/todos/
Traceback (most recent call last):
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\rest_framework\viewsets.py", line 114, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\rest_framework\views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\rest_framework\views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\rest_framework\views.py", line 476, in raise_uncaught_exception
    raise exc
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\rest_framework\views.py", line 502, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\rest_framework\mixins.py", line 43, in list
    return self.get_paginated_response(serializer.data)
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\rest_framework\serializers.py", line 760, in data
    ret = super().data
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\rest_framework\serializers.py", line 260, in data
    self._data = self.to_representation(self.instance)
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\rest_framework\serializers.py", line 677, in to_representation
    return [
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\rest_framework\serializers.py", line 678, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "C:\Users\warre\Desktop\Github\StoneFiles2020\summer\0717\venv\lib\site-packages\rest_framework\serializers.py", line 161, in to_representation
    raise NotImplementedError('`to_representation()` must be implemented.')
NotImplementedError: `to_representation()` must be implemented.
```

**Comment by VdeJong** [comment]
This is not a bug. BaseSerializer doesn't include a to_representation() method. Use `ModelSerializer` instead for example.
