### ISSUE TITLE
AutoSchema'd OpenAPI schemas are valid in JSON, but not in YAML

### ISSUE THREAD

**Issue by adamf** [encode/django-rest-framework#7479]
## Checklist

- [] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Given an autoschema generated YAML schema:

```
openapi: 3.0.2
info:
  title: REST API
  version: 1.0.0a
  description: API
paths:
  /_/api/users/{username}/:
    put:
      operationId: updateQUser
      description: API endpoint that allows users to be viewed or edited.
      parameters:
      - name: username
        in: path
        required: true
        description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
          only.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema: &id002
              properties:
                username:
                  type: string
                  description: Required. 150 characters or fewer. Letters, digits
                    and @/./+/-/_ only.
                  pattern: ^[\w.@+-]+\Z
                  maxLength: 150
              required:
              - username
          application/x-www-form-urlencoded:
            schema: *id002
          multipart/form-data:
            schema: *id002
      responses:
        '200':
          content:
            application/json:
              schema:
                properties:
                  url:
                    type: string
                    readOnly: true
                  username:
                    type: string
                    description: Required. 150 characters or fewer. Letters, digits
                      and @/./+/-/_ only.
                    pattern: ^[\w.@+-]+\Z
                    maxLength: 150
                  repo_owner:
                    type: array
                    items:
                      type: string
                    readOnly: true
                required:
                - username
          description: ''
```

Running openapi-generator on this fails to validate the schema:
```
openapi-generator generate -v -i test-schema.yaml -g python --package-name test -o test
[main] INFO  o.o.c.config.CodegenConfigurator -
VERBOSE MODE: ON. Additional debug options are injected
 - [debugOpenAPI] prints the OpenAPI specification as interpreted by the codegen
 - [debugModels] prints models passed to the template engine
 - [debugOperations] prints operations passed to the template engine
 - [debugSupportingFiles] prints additional data passed to the template engine
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 2, Warning count: 0
Errors:
	-attribute paths.'/_/api/users/{username}/'(put).requestBody.content.'application/x-www-form-urlencoded'.schema is not of type `object`
	-attribute paths.'/_/api/users/{username}/'(put).requestBody.content.'multipart/form-data'.schema is not of type `object`

	at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:480)
	at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:507)
	at org.openapitools.codegen.cmd.Generate.execute(Generate.java:423)
	at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
	at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:61)
```

```
$ openapi-generator version
4.3.1
```

Interestingly, if I use the same AutoSchema generated schema but in JSON format, I get no errors - hence this bug.

## Expected behavior

`openapi-generator` is able to validate the schema and generated code.

## Actual behavior

`openapi-generator` fails as shown above.

Any ideas? Happy to test more.

**Comment by carltongibson** [comment]
Hi. 

> Any ideas?

Not immediately 😀

Really happy for you to pin it down further. Why should it be valid as JSON but not YAML? 

Are we just missing a `'type':'object'`, which is the first thing that comes to mind reading the error? -- but that doesn't explain at all why it'd be valid as JSON... 🧐

**Comment by adamf** [comment]
Here's the same schema section in JSON; the big difference is it doesn't use the `*id/&id` syntax that the yaml has. 

```
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "username": {
                    "type": "string",
                    "description": "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                    "pattern": "^[\\w.@+-]+\\Z",
                    "maxLength": 150
                  }
                },
                "required": [
                  "username"
                ]
              }
            },
            "application/x-www-form-urlencoded": {
              "schema": {
                "properties": {
                  "username": {
                    "type": "string",
                    "description": "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                    "pattern": "^[\\w.@+-]+\\Z",
                    "maxLength": 150
                  }
                },
                "required": [
                  "username"
                ]
              }
            },
            "multipart/form-data": {
              "schema": {
                "properties": {
                  "username": {
                    "type": "string",
                    "description": "Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                    "pattern": "^[\\w.@+-]+\\Z",
                    "maxLength": 150
                  }
                },
                "required": [
                  "username"
                ]
              }
            }
          }
        },
```


If I add explicit definitions for each content type the generation works:

```
      requestBody:
        content:
          application/json:
            schema: &id002
              type: object
              properties:
                username:
                  type: string
                  description: Required. 150 characters or fewer. Letters, digits
                    and @/./+/-/_ only.
                  pattern: ^[\w.@+-]+\Z
                  maxLength: 150
              required:
              - username
          application/x-www-form-urlencoded:
            schema: &id002
              type: object
              properties:
                username:
                  type: string
                  description: Required. 150 characters or fewer. Letters, digits
                    and @/./+/-/_ only.
                  pattern: ^[\w.@+-]+\Z
                  maxLength: 150
              required:
              - username
          multipart/form-data:
            schema: &id002
              type: object
              properties:
                username:
                  type: string
                  description: Required. 150 characters or fewer. Letters, digits
                    and @/./+/-/_ only.
                  pattern: ^[\w.@+-]+\Z
                  maxLength: 150
              required:
              - username
```

So I think that the issue is the generated YAML's schema callbacks are not correct or understood by `openapi-generator`.

**Comment by carltongibson** [comment]
Can I ask you to open an issue with openapi-generator and link here? (I'll close assuming it's not our issue.) Thanks for the report!

**Comment by tomchristie** [comment]
Alrighty, so the validation error is being caused by `pyyaml` using anchors & aliases... https://ttl255.com/yaml-anchors-and-aliases-and-how-to-disable-them/

This has been resolved in https://github.com/encode/django-rest-framework/pull/7131 which will be present in our next release (which is currently the highest priority item on my TODO).

If you need a fix in the meantime you'd want to pass a custom renderer to the schema view.

Something along these lines...

```python
class OpenAPIRenderer(BaseRenderer):
    media_type = 'application/vnd.oai.openapi'
    charset = None
    format = 'openapi'

    def render(self, data, media_type=None, renderer_context=None):
        # disable yaml advanced feature 'alias' for clean, portable, and readable output
        class Dumper(yaml.Dumper):
            def ignore_aliases(self, data):
                return True
        return yaml.dump(data, default_flow_style=False, sort_keys=False, Dumper=Dumper).encode('utf-8')

schema_view = get_schema_view(..., renderer_classes=[OpenAPIRenderer])
```

**Comment by adamf** [comment]
Sweet, thanks! We can wait until the next release for this, appreciate it!
