### ISSUE TITLE
return Response(serializer.data) error but response object is work

### ISSUE THREAD

**Issue by sleep2144985** [encode/django-rest-framework#7543]
Here is full stacktrace
```
Traceback (most recent call last):
  File "/Users/wuqilun/opt/anaconda3/envs/agatha/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/wuqilun/opt/anaconda3/envs/agatha/lib/python3.6/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/wuqilun/opt/anaconda3/envs/agatha/lib/python3.6/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/Users/wuqilun/opt/anaconda3/envs/agatha/lib/python3.6/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/wuqilun/opt/anaconda3/envs/agatha/lib/python3.6/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/Users/wuqilun/opt/anaconda3/envs/agatha/lib/python3.6/site-packages/rest_framework/renderers.py", line 724, in render
    context = self.get_context(data, accepted_media_type, renderer_context)
  File "/Users/wuqilun/opt/anaconda3/envs/agatha/lib/python3.6/site-packages/rest_framework/renderers.py", line 656, in get_context
    raw_data_put_form = self.get_raw_data_form(data, view, 'PUT', request)
  File "/Users/wuqilun/opt/anaconda3/envs/agatha/lib/python3.6/site-packages/rest_framework/renderers.py", line 563, in get_raw_data_form
    data = serializer.data.copy()
  File "/Users/wuqilun/opt/anaconda3/envs/agatha/lib/python3.6/site-packages/rest_framework/serializers.py", line 563, in data
    return ReturnDict(ret, serializer=self)
  File "/Users/wuqilun/opt/anaconda3/envs/agatha/lib/python3.6/site-packages/rest_framework/utils/serializer_helpers.py", line 18, in __init__
    super().__init__(*args, **kwargs)
TypeError: 'NoneType' object is not iterable
```
my serializer :
```
class RetrieveOpenExtractionSerializer(serializers.ModelSerializer):
    username = serializers.CharField(source='owner.name', read_only=True)
    dataset_name = serializers.CharField(source='api_token.extraction.dataset.name', read_only=True)
    time = serializers.DateTimeField(read_only=True, default=None)
    cond_list = CondListSerializer(many=True, default=None)
    data = serializers.ListField(
        serializers.DictField(default=None)
    )
    status = serializers.ChoiceField(
        choices=['pending', 'finish', 'fail'],
        read_only=True
    )
    size = serializers.IntegerField(default=None, read_only=True)
    progress = serializers.CharField(default="0%")
    class Meta:
        model = AccessHistory
        fields = ('username', 'dataset_name', 'time', 'cond_list', 'data', 'status', 'size', 'progress')

    def to_representation(self, instance):
        is_processed = instance.is_processed
        ret = super().to_representation(instance)
        time = datetime.now()
        ret['time'] = time
        data = []
        if is_processed:
            with open(instance.output_file, 'r') as reader:
                data = json.loads(reader.read())
        ret['data'] = instance.api_token.extraction.dataset.format_data(data)
        ret['size'] = len(data)
        filter_list = instance.generate_extraction_list()
        ret['cond_list'] = [{'order': idx, 'cond': filter_list[idx].cond} for idx in range(len(filter_list))]
        ret['status'] = instance.status
        ret['progress'] =  "{:.0%}".format(instance.current_progress/instance.progress_size)
        return ret
```
views(default rest_framework retrieve function):
```
def retrieve(self, request, pk):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        return Response(serializer.data)
```
and print(Response(serializer.data)):
```
<Response status_code=200, "text/html; charset=utf-8">
```
but I override view
```
def retrieve(self, request, pk):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        return Response(dict(serializer.data))
```
it is work, i don't know why.

**Comment by tomchristie** [comment]
Hi there & thanks for your question.

The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions.

Thanks! 😀
