### ISSUE TITLE
Model Token is not registered after upgrading 3.11.2 to 3.12.2

### ISSUE THREAD

**Issue by triplethreatsolutions** [encode/django-rest-framework#7658]
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Upgrade from djangorestframework==3.11.2 to 3.12.2

**from rest_framework.authtoken.models import Token
admin.site.unregister(Token)**

Run python manage.py test

## Expected behavior
Tests to pass

## Actual behavior
Traceback (most recent call last):
  File "manage.py", line 38, in <module>
    execute_from_command_line(sys.argv)
  File "...\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "...\lib\site-packages\django\core\management\__init__.py", line 357, in execute
    django.setup()
  File "...\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "...\lib\site-packages\django\apps\registry.py", line 122, in populate
    app_config.ready()
  File "...\lib\site-packages\django\contrib\admin\apps.py", line 24, in ready
    self.module.autodiscover()
  File "...\lib\site-packages\django\contrib\admin\__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "...\lib\site-packages\django\utils\module_loading.py", line 47, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "C:\Python38-2\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "...\users\admin.py", line 24, in <module>
    admin.site.unregister(Token)
  **File "...\lib\site-packages\django\contrib\admin\sites.py", line 136, in unregister
    raise NotRegistered('The model %s is not registered' % model.__name__)
django.contrib.admin.sites.NotRegistered: The model Token is not registered**

**Comment by kevin-brown** [comment]
This change happened in https://github.com/encode/django-rest-framework/pull/7341 where instead of auto-registering the `Token` model and using the primary key set by it, we are now registering a proxy model called `TokenProxy` which is the one that must be unregistered now.

I can't find anywhere in the documentation where we are recommending people unregister the default admin, but the easy solution is to unregister the `TokenProxy` now if you want to do something special.
