### ISSUE TITLE
meaning of get_by_natural_key

### ISSUE THREAD

**Issue by yash0307jain** [encode/django-rest-framework#7692]
When I tried to use my model as AUTH_USER_MODEL, I am getting this error:

```
AttributeError: 'Manager' object has no attribute 'get_by_natural_key'
```

models.py:

```
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=50)
    email = models.CharField(max_length=30, unique=True)
    password = models.CharField(max_length=30)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = [
        'name',
        'password'
    ]
    is_anonymous = []
    is_authenticated = []
```

Complete error:

```
System check identified no issues (0 silenced).
January 17, 2021 - 07:20:16
Django version 3.1.5, using settings 'django_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
Internal Server Error: /api/token
Traceback (most recent call last):
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\rest_framework_simplejwt\views.py", line 27, in post
    serializer.is_valid(raise_exception=True)
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\rest_framework\serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\rest_framework\serializers.py", line 422, in run_validation
    value = self.validate(value)
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\rest_framework_simplejwt\serializers.py", line 70, in validate
    data = super().validate(attrs)
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\rest_framework_simplejwt\serializers.py", line 49, in validate
    self.user = authenticate(**authenticate_kwargs)
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\django\contrib\auth\__init__.py", line 73, in authenticate
    user = backend.authenticate(request, **credentials)
  File "C:\Users\Smart\Envs\django-env\lib\site-packages\django\contrib\auth\backends.py", line 42, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
AttributeError: 'Manager' object has no attribute 'get_by_natural_key'
[17/Jan/2021 07:27:26] "POST /api/token HTTP/1.1" 500 123429
```

**Comment by Kashish-2001** [comment]
Make sure to add `AUTH_USER_MODEL = 'myapp.MyUser'` in settings.py of the Django project.
Here, `myapp` is the name of that Django app (which must be in your INSTALLED_APPS) and `MyUser` is the name of the Django model that you wish to use as your user model. 

Do this before creating any migrations or running manage.py migrate for the first time.
and make sure to register the model in the app’s admin.py :-

```
from .models import MyUser

admin.site.register(MyUser)
```

If still getting the error, follow the steps from this [link](https://docs.djangoproject.com/en/3.1/topics/auth/customizing/#substituting-a-custom-user-model).
