### ISSUE TITLE
ImportError: cannot import name 'ISO_8601' from 'rest_framework' (unknown location)

### ISSUE THREAD

**Issue by qcymkxyc** [encode/django-rest-framework#8070]
### Discussed in https://github.com/encode/django-rest-framework/discussions/8069

<div type='discussions-op-text'>

<sup>Originally posted by **qcymkxyc** July  7, 2021</sup>
I tried many times,when I run app this error appear</div>

**Comment by qcymkxyc** [comment]
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "D:\Program Files (x86)\python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "D:\Program Files (x86)\python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Program Files (x86)\python37\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "D:\Program Files (x86)\python37\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "D:\Program Files (x86)\python37\lib\site-packages\django\core\management\base.py", line 396, in check
    databases=databases,
  File "D:\Program Files (x86)\python37\lib\site-packages\django\core\checks\registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "D:\Program Files (x86)\python37\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "D:\Program Files (x86)\python37\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "D:\Program Files (x86)\python37\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Program Files (x86)\python37\lib\site-packages\django\urls\resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\Program Files (x86)\python37\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\Program Files (x86)\python37\lib\site-packages\django\urls\resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "D:\Program Files (x86)\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\zq\PyCharmProject\watermarker_project\watermarker\urls.py", line 23, in <module>
    url("^user/", include("user.urls")),
  File "D:\Program Files (x86)\python37\lib\site-packages\django\urls\conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "D:\Program Files (x86)\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\zq\PyCharmProject\watermarker_project\user\urls.py", line 17, in <module>
    from user import views
  File "F:\zq\PyCharmProject\watermarker_project\user\views.py", line 3, in <module>
    from rest_framework import viewsets
  File "D:\Program Files (x86)\python37\lib\site-packages\rest_framework\viewsets.py", line 27, in <module>
    from rest_framework import generics, mixins, views
  File "D:\Program Files (x86)\python37\lib\site-packages\rest_framework\generics.py", line 9, in <module>
    from rest_framework import mixins, views
  File "D:\Program Files (x86)\python37\lib\site-packages\rest_framework\mixins.py", line 8, in <module>
    from rest_framework.response import Response
  File "D:\Program Files (x86)\python37\lib\site-packages\rest_framework\response.py", line 11, in <module>
    from rest_framework.serializers import Serializer
  File "D:\Program Files (x86)\python37\lib\site-packages\rest_framework\serializers.py", line 29, in <module>
    from rest_framework.fields import get_error_detail, set_value
  File "D:\Program Files (x86)\python37\lib\site-packages\rest_framework\fields.py", line 34, in <module>
    from rest_framework import (
ImportError: cannot import name 'ISO_8601' from 'rest_framework' (unknown location)
