### ISSUE TITLE
MkDocs 1.1.2 Uses Buggy Jinja2 Version

### ISSUE THREAD

**Issue by hashlash** [encode/django-rest-framework#8432]
When building the docs, it gives [error](https://github.com/encode/django-rest-framework/runs/5706289348?check_suite_focus=true#step:7:1369):

```
Traceback (most recent call last):
  File "/home/runner/work/django-rest-framework/django-rest-framework/.tox/venvs/docs/bin/mkdocs", line 5, in <module>
    from mkdocs.__main__ import cli
  File "/home/runner/work/django-rest-framework/django-rest-framework/.tox/venvs/docs/lib/python3.9/site-packages/mkdocs/__main__.py", line 16, in <module>
    from mkdocs import config                                 # noqa: E402
  File "/home/runner/work/django-rest-framework/django-rest-framework/.tox/venvs/docs/lib/python3.9/site-packages/mkdocs/config/__init__.py", line 2, in <module>
    from mkdocs.config.defaults import DEFAULT_SCHEMA
  File "/home/runner/work/django-rest-framework/django-rest-framework/.tox/venvs/docs/lib/python3.9/site-packages/mkdocs/config/defaults.py", line 1, in <module>
    from mkdocs.config import config_options
  File "/home/runner/work/django-rest-framework/django-rest-framework/.tox/venvs/docs/lib/python3.9/site-packages/mkdocs/config/config_options.py", line 7, in <module>
    from mkdocs import utils, theme, plugins
  File "/home/runner/work/django-rest-framework/django-rest-framework/.tox/venvs/docs/lib/python3.9/site-packages/mkdocs/theme.py", line 6, in <module>
    from mkdocs.utils import filters
  File "/home/runner/work/django-rest-framework/django-rest-framework/.tox/venvs/docs/lib/python3.9/site-packages/mkdocs/utils/filters.py", line 11, in <module>
    @jinja2.contextfilter
AttributeError: module 'jinja2' has no attribute 'contextfilter'
```

The source of error: https://github.com/mkdocs/mkdocs/issues/2799

_Originally posted by @hashlash in https://github.com/encode/django-rest-framework/issues/8429#issuecomment-1078626863_

**Comment by tomchristie** [comment]
Closing since https://github.com/mkdocs/mkdocs/issues/2799 is now resolved.
