### ISSUE TITLE
Get an error when I practice following tutorial 4

### ISSUE THREAD

**Issue by kev26** [encode/django-rest-framework#8505]
### Discussed in https://github.com/encode/django-rest-framework/discussions/8504

<div type='discussions-op-text'>

<sup>Originally posted by **kev26** May 30, 2022</sup>
when I try to create superuser in the [tutorial 4](https://www.django-rest-framework.org/tutorial/4-authentication-and-permissions/), I got the error:
`django.db.utils.IntegrityError: NOT NULL constraint failed: auth_user.last_login`

`Traceback (most recent call last):
  File "D:\code\restfullapi\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\restfullapi\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.IntegrityError: NOT NULL constraint failed: auth_user.last_login

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\code\restfullapi\tutorial\manage.py", line 22, in <module>
    main()
  File "D:\code\restfullapi\tutorial\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "D:\code\restfullapi\env\lib\site-packages\django\core\management\__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "D:\code\restfullapi\env\lib\site-packages\django\core\management\__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\code\restfullapi\env\lib\site-packages\django\core\management\base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\code\restfullapi\env\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 87, in execute
    return super().execute(*args, **options)
  File "D:\code\restfullapi\env\lib\site-packages\django\core\management\base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "D:\code\restfullapi\env\lib\site-packages\django\contrib\auth\management\commands\createsuperuser.py", line 232, in handle
    self.UserModel._default_manager.db_manager(database).create_superuser(
  File "D:\code\restfullapi\env\lib\site-packages\django\contrib\auth\models.py", line 171, in create_superuser
    return self._create_user(username, email, password, **extra_fields)
  File "D:\code\restfullapi\env\lib\site-packages\django\contrib\auth\models.py", line 154, in _create_user
    user.save(using=self._db)
  File "D:\code\restfullapi\env\lib\site-packages\django\contrib\auth\base_user.py", line 68, in save
    super().save(*args, **kwargs)
  File "D:\code\restfullapi\env\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\code\restfullapi\env\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\code\restfullapi\env\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\code\restfullapi\env\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\code\restfullapi\env\lib\site-packages\django\db\models\sql\compiler.py", line 1621, in execute_sql
    cursor.execute(sql, params)
  File "D:\code\restfullapi\env\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "D:\code\restfullapi\env\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\code\restfullapi\env\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\code\restfullapi\env\lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "D:\code\restfullapi\env\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\code\restfullapi\env\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\code\restfullapi\env\lib\site-packages\django\db\backends\sqlite3\base.py", line 477, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.IntegrityError: NOT NULL constraint failed: auth_user.last_login`</div>

**Comment by kev26** [comment]
Ya! I run `python manage.py migrate` instead of `python manage.py migrate snippets` will resolve this problem!
