### ISSUE TITLE
why can't "try except"  catch TypeError in DRF？

### ISSUE THREAD

**Issue by boziyoung** [encode/django-rest-framework#8646]
my Reproduction code view:
`@action(methods=["get"], detail=True, url_path= "get_code")
    def get_code(self, request, pk):
     
        try:
            queryset = Depot.objects.get(code=pk)
            serializer = self.get_serializer(queryset)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except Exception as msg:
            return Response(msg, status=status.HTTP_403_FORBIDDEN)`

view raise error:
Internal Server Error: /depot/1/get_code/
Traceback (most recent call last):
  File "/home/ubuntu/grocery/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/ubuntu/grocery/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 220, in _get_response
    response = response.render()
  File "/home/ubuntu/grocery/env/lib/python3.8/site-packages/django/template/response.py", line 114, in render
    self.content = self.rendered_content
  File "/home/ubuntu/grocery/env/lib/python3.8/site-packages/rest_framework/response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "/home/ubuntu/grocery/env/lib/python3.8/site-packages/rest_framework/renderers.py", line 100, in render
    ret = json.dumps(
  File "/home/ubuntu/grocery/env/lib/python3.8/site-packages/rest_framework/utils/json.py", line 25, in dumps
    return json.dumps(*args, **kwargs)
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/ubuntu/grocery/env/lib/python3.8/site-packages/rest_framework/utils/encoders.py", line 67, in default
    return super().default(obj)
  File "/usr/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DoesNotExist is not JSON serializable

who can tell me what should I do?

**Comment by oktayxpolat** [comment]
I guess firstly it catches the exception DoesNotExist and falls to the except statement. There you give the msg which equals to DoesNotExist here as an argument to the Response and you get the TypeError exception there. That's why it is not caught.

**Comment by tomchristie** [comment]
You're looking for this I think...

```python

except Exception as exc:
        msg = str(exc)
        return Response(msg, status=status.HTTP_403_FORBIDDEN)
```

**Comment by boziyoung** [comment]
ok, thank you, sir
