### ISSUE TITLE
Schemas generators "__init__() missing 1 required positional argument: 'container'"

### ISSUE THREAD

**Issue by KevinRuanSoares** [encode/django-rest-framework#8881]
- Python 3.8
- Django 3.2.17
- Django Rest Framework 3.14.0

I recently performed the update from Django 2.2 to version 3.2 after that when trying to generate the project documentation the following error is returned to me:

`Traceback (most recent call last):
  File "manage.py", line 19, in <module>
    execute_from_command_line(sys.argv)
  File "/path_venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/path_venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/path_venv/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/path_venv/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/path_venv/lib/python3.8/site-packages/rest_framework/management/commands/generateschema.py", line 43, in handle
    schema = generator.get_schema(request=None, public=True)
  File "/path_venv/lib/python3.8/site-packages/rest_framework/schemas/openapi.py", line 71, in get_schema
    self._initialise_endpoints()
  File "/path_venv/lib/python3.8/site-packages/rest_framework/schemas/generators.py", line 171, in _initialise_endpoints
    self.endpoints = inspector.get_api_endpoints()
  File "/path_venv/lib/python3.8/site-packages/rest_framework/schemas/generators.py", line 92, in get_api_endpoints
    nested_endpoints = self.get_api_endpoints(
  File "/path_venv/lib/python3.8/site-packages/rest_framework/schemas/generators.py", line 87, in get_api_endpoints
    for method in self.get_allowed_methods(callback):
  File "/path_venv/lib/python3.8/site-packages/rest_framework/schemas/generators.py", line 141, in get_allowed_methods
    methods = callback.cls().allowed_methods
TypeError: __init__() missing 1 required positional argument: 'container'`

**Comment by iameo** [comment]
Could you be so kind to drop an exempt of the affected code?

**Comment by KevinRuanSoares** [comment]
The project runs normally the problem is presented when I try to generate the swagger documentation.

**Comment by tomchristie** [comment]
ENOTENOUGHINFO
