### ISSUE TITLE
Too much data for declared Content-Length

### ISSUE THREAD

**Issue by sh1man999** [encode/django-rest-framework#9557]
i use djangorestframework 3.15.2
django 5.1.1
and webserver uvicorn

```
class SpaceViewSet(ModelViewSet):
    queryset = Space.objects.all()
```

```
INFO:     127.0.0.1:61374 - "DELETE /api/address/spaces/876/ HTTP/1.1" 204 No Content
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\analytic-barrier-web-scTd73e0-py3.10\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\analytic-barrier-web-scTd73e0-py3.10\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\analytic-barrier-web-scTd73e0-py3.10\lib\site-packages\engineio\async_drivers\asgi.py", line 74, in __call__
    await self.other_asgi_app(scope, receive, send)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\analytic-barrier-web-scTd73e0-py3.10\lib\site-packages\django\core\handlers\asgi.py", line 162, in __call__
    await self.handle(scope, receive, send)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\analytic-barrier-web-scTd73e0-py3.10\lib\site-packages\django\core\handlers\asgi.py", line 208, in handle
    task.result()
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\analytic-barrier-web-scTd73e0-py3.10\lib\site-packages\django\core\handlers\asgi.py", line 187, in process_request
    await self.send_response(response, send)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\analytic-barrier-web-scTd73e0-py3.10\lib\site-packages\django\core\handlers\asgi.py", line 349, in send_response
    await send(
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\analytic-barrier-web-scTd73e0-py3.10\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 503, in send
    output = self.conn.send(event=h11.Data(data=data))
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\analytic-barrier-web-scTd73e0-py3.10\lib\site-packages\h11\_connection.py", line 512, in send
    data_list = self.send_with_data_passthrough(event)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\analytic-barrier-web-scTd73e0-py3.10\lib\site-packages\h11\_connection.py", line 545, in send_with_data_passthrough
    writer(event, data_list.append)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\analytic-barrier-web-scTd73e0-py3.10\lib\site-packages\h11\_writers.py", line 65, in __call__
    self.send_data(event.data, write)
  File "C:\Users\user\AppData\Local\pypoetry\Cache\virtualenvs\analytic-barrier-web-scTd73e0-py3.10\lib\site-packages\h11\_writers.py", line 91, in send_data
    raise LocalProtocolError("Too much data for declared Content-Length")
h11._util.LocalProtocolError: Too much data for declared Content-Length
```

If I override, there are no errors

```
def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        self.perform_destroy(instance)
        return HttpResponse(status=status.HTTP_204_NO_CONTENT)
```

At what point does DRF add Data ?

**Comment by tomchristie** [comment]
You're sending a malformed request, and the server is responding with an error.

**Comment by sh1man999** [comment]
Then why does it solve the problem ?
```
def destroy(self, request, *args, **kwargs):
        instance = self.get_object()
        self.perform_destroy(instance)
        return HttpResponse(status=status.HTTP_204_NO_CONTENT)
```
